version: '3.8'

services:
  app:
     container_name: python_app
     build: ./
     depends_on:
       - db
     volumes:
       - ./:/code
     ports:
       - ${APP_HOST_PORT}:80
     restart: always
     env_file:
       - .env


  db:
    container_name: project_postgres
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_HOST_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always